#!/usr/bin/env bash
set -euo pipefail

f="populate/01_populate.sh"
[ -f "$f" ] || { echo "ERROR: $f not found" >&2; exit 1; }

# Insert command registry + executor stub block before populated_files=( if not present
if ! grep -q 'command_registry.json' "$f"; then
  awk '
    BEGIN{inserted=0}
    /populated_files=\(/ && inserted==0 {
      print ""
      print "# -----------------------------"
      print "# Phase 0.5 — Command Registry"
      print "# -----------------------------"
      print ""
      print "cat > runtime/schema/command_registry.json <<'\''EOT'\''"
      print "{"
      print "  \"schema_version\": \"0.1\","
      print "  \"contract\": \"command_registry\","
      print "  \"commands\": {"
      print "    \"noop\": {"
      print "      \"description\": \"No operation. Validation-only.\","
      print "      \"required_capabilities\": {"
      print "        \"host\": \"none\","
      print "        \"context\": \"none\","
      print "        \"runtime\": \"read\","
      print "        \"command\": \"none\","
      print "        \"financial\": \"none\""
      print "      },"
      print "      \"args_schema\": {"
      print "        \"type\": \"object\","
      print "        \"additionalProperties\": false,"
      print "        \"properties\": {}"
      print "      }"
      print "    },"
      print "    \"validate\": {"
      print "      \"description\": \"Validate a request against schemas only.\","
      print "      \"required_capabilities\": {"
      print "        \"host\": \"none\","
      print "        \"context\": \"none\","
      print "        \"runtime\": \"read\","
      print "        \"command\": \"read\","
      print "        \"financial\": \"none\""
      print "      },"
      print "      \"args_schema\": {"
      print "        \"type\": \"object\","
      print "        \"additionalProperties\": false,"
      print "        \"properties\": {"
      print "          \"command\": {\"type\": \"string\"},"
      print "          \"args\": {\"type\": \"object\"}"
      print "        },"
      print "        \"required\": [\"command\", \"args\"]"
      print "      }"
      print "    }"
      print "  }"
      print "}"
      print "EOT"
      print ""
      print "# runtime/core/executor.py — validation-only stub (no IO, no external calls)"
      print "cat > runtime/core/executor.py <<'\''EOT'\''"
      print "from __future__ import annotations"
      print "from dataclasses import dataclass"
      print "from typing import Dict, Any"
      print ""
      print "from .capability import CapabilityLattice, execution_allowed"
      print ""
      print ""
      print "@dataclass(frozen=True)"
      print "class ExecutionContext:"
      print "    host: str"
      print "    context: str"
      print "    runtime: str"
      print "    command: str"
      print "    financial: str"
      print ""
      print ""
      print "class RegistryError(Exception):"
      print "    pass"
      print ""
      print ""
      print "def validate_command_request(registry: Dict[str, Any], name: str, args: Dict[str, Any]) -> None:"
      print "    if name not in registry.get(\"commands\", {}):"
      print "        raise RegistryError(f\"Unknown command: {name}\")"
      print "    # Args schema validation is deferred (no jsonschema dependency in Phase 0)."
      print "    if not isinstance(args, dict):"
      print "        raise RegistryError(\"args must be an object\")"
      print ""
      print ""
      print "def capabilities_for_command(registry: Dict[str, Any], name: str) -> Dict[str, str]:"
      print "    cmd = registry[\"commands\"][name]"
      print "    return cmd[\"required_capabilities\"]"
      print ""
      print ""
      print "def can_execute(lattice: CapabilityLattice, ctx: ExecutionContext, req: Dict[str, str]) -> bool:"
      print "    return execution_allowed(lattice, ctx.host, ctx.context, ctx.runtime, ctx.command, ctx.financial) and \\"
      print "           execution_allowed(lattice, req[\"host\"], req[\"context\"], req[\"runtime\"], req[\"command\"], req[\"financial\"])"
      print "EOT"
      print ""
      inserted=1
    }
    {print}
  ' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
fi

# Ensure populated_files includes the new outputs
if ! grep -q 'runtime/schema/command_registry.json' "$f"; then
  sed -i '/populated_files=(/a\  runtime/schema/command_registry.json\n  runtime/core/executor.py' "$f"
fi

echo "OK: populate/01_populate.sh patched for command registry."
